export const ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  DASHBOARD: "/dashboard",
  CAREER_ASSESSMENT: "/dashboard/career-assessment",
  ROADMAPS: "/dashboard/roadmaps",
  RESUMES: "/dashboard/resumes",
  RESUME_BUILDER: "/dashboard/resumes/builder",
  INTERVIEWS: "/dashboard/interviews",
  PROGRESS: "/dashboard/progress",
  PROFILE: "/dashboard/profile",
  SETTINGS: "/dashboard/settings",
  ONBOARDING: "/dashboard/onboarding",
} as const;
