"use server";

import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";
import { InterviewRequest } from "../types";
import { InterviewRequestSchema } from "../schemas/interview-request.schema";
import {
  JobType,
  JobStatus,
  InterviewStatus,
  InterviewType,
  InterviewTemplateStatus,
  InterviewTemplateSource,
  CareerExperienceLevel,
} from "@prisma/client";
import { tasks } from "@trigger.dev/sdk/v3";
import { generateInterviewTask } from "@/trigger/generate-interview";
import { GlobalInterviewTemplateService } from "../services/global-interview-template.service";
import { InterviewArtifactService } from "../services/interview-artifact.service";

function mapInterviewType(type: string): InterviewType {
  const norm = type.toUpperCase().replace(/[\s-]+/g, "_");
  if (norm.includes("BEHAVIORAL")) return InterviewType.BEHAVIORAL;
  if (norm.includes("SYSTEM_DESIGN")) return InterviewType.SYSTEM_DESIGN;
  if (norm.includes("ROLE_SPECIFIC")) return InterviewType.ROLE_SPECIFIC;
  if (norm.includes("GENERAL")) return InterviewType.GENERAL;
  return InterviewType.TECHNICAL;
}

function mapExperienceLevel(level: string): CareerExperienceLevel {
  const upper = level.toUpperCase();
  if (upper === "BEGINNER" || upper === "ENTRY") return CareerExperienceLevel.ENTRY;
  if (upper === "JUNIOR") return CareerExperienceLevel.JUNIOR;
  if (upper === "ADVANCED" || upper === "SENIOR") return CareerExperienceLevel.SENIOR;
  if (upper === "LEAD") return CareerExperienceLevel.LEAD;
  return CareerExperienceLevel.MID;
}

export async function createInterviewJob(request: InterviewRequest) {
  const { userId: clerkId } = await auth();

  if (!clerkId) {
    throw new Error("Unauthorized: You must be logged in to generate an interview.");
  }

  // Find DB User
  const dbUser = await prisma.user.findUnique({
    where: { clerkId },
  });

  if (!dbUser) {
    throw new Error("User record not found.");
  }

  // Validate incoming request
  const validatedRequest = InterviewRequestSchema.parse(request);
  const targetQuestionCount = validatedRequest.questionCount || 10;
  const mappedInterviewType = mapInterviewType(validatedRequest.interviewType);
  const mappedExpLevel = mapExperienceLevel(validatedRequest.experienceLevel);

  const isPersonalized = !validatedRequest.personalization.skipped;

  // ============================================================
  // CASE A: Generic Interview (Check for existing Global Template)
  // ============================================================
  if (!isPersonalized) {
    const existingGlobalTemplate = await GlobalInterviewTemplateService.findMatchingTemplate(
      validatedRequest.role,
      mappedExpLevel,
      mappedInterviewType
    );

    if (existingGlobalTemplate) {
      if (existingGlobalTemplate.templateBlobUrl && existingGlobalTemplate.templateBlobUrl.trim() !== "") {
        // Instant Cache Hit: Reuse existing canonical template blob directly (No LLM, No Trigger.dev, No Blob cloning)
        const session = await prisma.interviewSession.create({
          data: {
            userId: dbUser.id,
            globalInterviewTemplateId: existingGlobalTemplate.id,
            templateSource: InterviewTemplateSource.GLOBAL,
            role: validatedRequest.role,
            experienceLevel: mappedExpLevel,
            interviewType: mappedInterviewType,
            questionCount: existingGlobalTemplate.questionCount || targetQuestionCount,
            estimatedDuration: existingGlobalTemplate.estimatedDuration,
            blobUrl: existingGlobalTemplate.templateBlobUrl,
            status: InterviewStatus.READY,
            personalized: false,
          },
        });

        // Create completed tracking job
        const job = await prisma.job.create({
          data: {
            userId: dbUser.id,
            type: JobType.INTERVIEW,
            status: JobStatus.COMPLETED,
            progress: 100,
            step: "Ready",
            artifactId: session.id,
            artifactType: "GLOBAL_INTERVIEW_TEMPLATE",
            completedAt: new Date(),
          },
        });

        return {
          interviewId: session.id,
          jobId: job.id,
          isReused: true,
        };
      }

      // Template is currently being generated by another job
      const activeJob = await prisma.job.findFirst({
        where: {
          artifactId: existingGlobalTemplate.id,
          status: { in: [JobStatus.QUEUED, JobStatus.RUNNING] },
        },
        orderBy: { createdAt: "desc" },
      });

      const session = await prisma.interviewSession.create({
        data: {
          userId: dbUser.id,
          globalInterviewTemplateId: existingGlobalTemplate.id,
          templateSource: InterviewTemplateSource.GLOBAL,
          role: validatedRequest.role,
          experienceLevel: mappedExpLevel,
          interviewType: mappedInterviewType,
          questionCount: existingGlobalTemplate.questionCount || targetQuestionCount,
          status: InterviewStatus.GENERATING,
          personalized: false,
        },
      });

      return {
        interviewId: session.id,
        jobId: activeJob?.id || null,
        isReused: true,
      };
    }

    // No existing global template found — create placeholder with race condition handling
    const normalizedRole = GlobalInterviewTemplateService.normalizeRole(validatedRequest.role);
    let globalTemplate;
    try {
      globalTemplate = await GlobalInterviewTemplateService.createTemplate({
        createdByUserId: dbUser.id,
        role: validatedRequest.role,
        normalizedRole,
        experienceLevel: mappedExpLevel,
        interviewType: mappedInterviewType,
        questionCount: targetQuestionCount,
        templateBlobUrl: "",
      });
    } catch (err: any) {
      if (err?.code === "P2002") {
        const raceTemplate = await GlobalInterviewTemplateService.findMatchingTemplate(
          validatedRequest.role,
          mappedExpLevel,
          mappedInterviewType
        );
        if (raceTemplate) {
          if (raceTemplate.templateBlobUrl && raceTemplate.templateBlobUrl.trim() !== "") {
            const session = await prisma.interviewSession.create({
              data: {
                userId: dbUser.id,
                globalInterviewTemplateId: raceTemplate.id,
                templateSource: InterviewTemplateSource.GLOBAL,
                role: validatedRequest.role,
                experienceLevel: mappedExpLevel,
                interviewType: mappedInterviewType,
                questionCount: raceTemplate.questionCount || targetQuestionCount,
                estimatedDuration: raceTemplate.estimatedDuration,
                blobUrl: raceTemplate.templateBlobUrl,
                status: InterviewStatus.READY,
                personalized: false,
              },
            });
            const job = await prisma.job.create({
              data: {
                userId: dbUser.id,
                type: JobType.INTERVIEW,
                status: JobStatus.COMPLETED,
                progress: 100,
                step: "Ready",
                artifactId: session.id,
                artifactType: "GLOBAL_INTERVIEW_TEMPLATE",
                completedAt: new Date(),
              },
            });
            return {
              interviewId: session.id,
              jobId: job.id,
              isReused: true,
            };
          }
        }
      }
      throw err;
    }

    const session = await prisma.interviewSession.create({
      data: {
        userId: dbUser.id,
        globalInterviewTemplateId: globalTemplate.id,
        templateSource: InterviewTemplateSource.GLOBAL,
        role: validatedRequest.role,
        experienceLevel: mappedExpLevel,
        interviewType: mappedInterviewType,
        questionCount: targetQuestionCount,
        status: InterviewStatus.GENERATING,
        personalized: false,
      },
    });

    const job = await prisma.job.create({
      data: {
        userId: dbUser.id,
        type: JobType.INTERVIEW,
        status: JobStatus.QUEUED,
        progress: 0,
        step: "Queued",
        artifactId: globalTemplate.id,
        artifactType: "GLOBAL_INTERVIEW_TEMPLATE",
      },
    });

    let triggerRunId: string | undefined;
    try {
      const handle = await tasks.trigger<typeof generateInterviewTask>(
        "generate-interview",
        {
          interviewId: session.id,
          jobId: job.id,
          userId: dbUser.id,
          templateSource: "GLOBAL",
          globalInterviewTemplateId: globalTemplate.id,
          request: {
            ...validatedRequest,
            questionCount: targetQuestionCount,
          },
        }
      );
      triggerRunId = handle.id;

      await prisma.job.update({
        where: { id: job.id },
        data: { triggerRunId },
      });
    } catch (error) {
      console.error("Failed to trigger Trigger.dev generate-interview task:", error);
      await prisma.job.update({
        where: { id: job.id },
        data: {
          status: JobStatus.FAILED,
          error: error instanceof Error ? error.message : "Trigger failed",
        },
      });
      await prisma.interviewSession.update({
        where: { id: session.id },
        data: { status: InterviewStatus.FAILED },
      });
      throw new Error("Failed to start background interview generation job.");
    }

    return {
      interviewId: session.id,
      jobId: job.id,
      triggerRunId,
    };
  }

  // ============================================================
  // CASE B: Personalized Interview (User-Owned Template)
  // ============================================================
  // Always fetch authoritative profile server-side
  const profile = await prisma.profile.findUnique({
    where: { userId: dbUser.id },
  });

  let profileSnapshot: Record<string, any> | null = null;
  if (profile) {
    // Select ONLY the 7 approved profile attributes
    profileSnapshot = {
      currentStatus: profile.currentStatus,
      currentRole: profile.currentRole,
      yearsOfExperience: profile.yearsOfExperience,
      highestQualification: profile.highestQualification,
      fieldOfStudy: profile.fieldOfStudy,
      primaryGoal: profile.primaryGoal,
      targetCompanyType: profile.targetCompanyType,
    };
  }

  // 1. Create InterviewTemplate record (user-owned)
  const template = await prisma.interviewTemplate.create({
    data: {
      userId: dbUser.id,
      role: validatedRequest.role,
      experienceLevel: mappedExpLevel,
      interviewType: mappedInterviewType,
      questionCount: targetQuestionCount,
      templateBlobUrl: "",
      status: InterviewTemplateStatus.ACTIVE,
      personalized: true,
      profileSnapshot: profileSnapshot || undefined,
    },
  });

  // 2. Create InterviewSession record
  const session = await prisma.interviewSession.create({
    data: {
      userId: dbUser.id,
      interviewTemplateId: template.id,
      templateSource: InterviewTemplateSource.USER_CREATED,
      role: validatedRequest.role,
      experienceLevel: mappedExpLevel,
      interviewType: mappedInterviewType,
      questionCount: targetQuestionCount,
      status: InterviewStatus.GENERATING,
      personalized: true,
      profileSnapshot: profileSnapshot || undefined,
    },
  });

  // 3. Create Job System record
  const job = await prisma.job.create({
    data: {
      userId: dbUser.id,
      type: JobType.INTERVIEW,
      status: JobStatus.QUEUED,
      progress: 0,
      step: "Queued",
      artifactId: session.id,
      artifactType: "INTERVIEW_TEMPLATE",
    },
  });

  // 4. Trigger background generation task
  let triggerRunId: string | undefined;
  try {
    const handle = await tasks.trigger<typeof generateInterviewTask>(
      "generate-interview",
      {
        interviewId: session.id,
        jobId: job.id,
        userId: dbUser.id,
        templateSource: "USER_CREATED",
        interviewTemplateId: template.id,
        request: {
          ...validatedRequest,
          questionCount: targetQuestionCount,
          personalization: {
            skipped: false,
            profile: profileSnapshot,
          },
        },
      }
    );
    triggerRunId = handle.id;

    await prisma.job.update({
      where: { id: job.id },
      data: { triggerRunId },
    });
  } catch (error) {
    console.error("Failed to trigger Trigger.dev generate-interview task:", error);
    await prisma.job.update({
      where: { id: job.id },
      data: {
        status: JobStatus.FAILED,
        error: error instanceof Error ? error.message : "Trigger failed",
      },
    });
    await prisma.interviewSession.update({
      where: { id: session.id },
      data: { status: InterviewStatus.FAILED },
    });
    throw new Error("Failed to start background interview generation job.");
  }

  return {
    interviewId: session.id,
    jobId: job.id,
    triggerRunId,
  };
}

