import { CheckCircle2, Sparkles } from "lucide-react";

export function Gallery() {
  const reports = [
    {
      title: "ATS Resume Analysis",
      tag: "Resume Report",
      score: "96%",
      badgeColor: "bg-[#84E6F6]",
      details: ["Keywords Matched: 28/30", "Formatting Score: 100%", "Quantified Bullets: 95%"],
      height: "h-64",
    },
    {
      title: "Full Career Roadmap",
      tag: "Trajectory Plan",
      score: "Level 6",
      badgeColor: "bg-[#FECD1A]",
      details: ["Target: Lead Architect", "Est. Timeline: 6 Months", "High-Priority Skills: 4"],
      height: "h-80",
    },
    {
      title: "System Design Evaluation",
      tag: "Interview Sim",
      score: "4.9/5",
      badgeColor: "bg-[#F7A49E]",
      details: ["Scalability Concept: Pass", "Tradeoff Explanation: Excellent", "Communication: High"],
      height: "h-72",
    },
    {
      title: "Offer Negotiation Brief",
      tag: "Compensation",
      score: "+$42,000",
      badgeColor: "bg-[#FEF7AF]",
      details: ["Base Target: $210k", "Equity Benchmark: Top 10%", "Counter Strategy: Included"],
      height: "h-64",
    },
  ];

  return (
    <section className="py-24 px-4 sm:px-6 max-w-container-max mx-auto">
      <div className="text-center max-w-2xl mx-auto mb-16 space-y-4">
        <span className="text-xs font-semibold uppercase tracking-widest text-[#999999]">Structured Output Samples</span>
        <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-black">
          Sample Reports
        </h2>
        <p className="text-lg text-[#605F5F]">
          Here is a glimpse of the detailed, actionable diagnostic reports generated by our AI engine.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 items-start">
        {reports.map((item, idx) => (
          <div
            key={idx}
            className={`bg-white border border-[#E6E6E6] rounded-2xl p-6 shadow-sm hover:shadow-md hover:-translate-y-1 transition-all duration-300 flex flex-col justify-between ${item.height}`}
          >
            <div>
              <div className="flex justify-between items-center mb-4">
                <span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full text-black ${item.badgeColor} border border-black/10`}>
                  {item.tag}
                </span>
                <Sparkles className="w-4 h-4 text-black opacity-60" />
              </div>
              <h3 className="text-lg font-bold text-black mb-1">{item.title}</h3>
              <div className="text-2xl font-black text-black mb-4">{item.score}</div>

              <ul className="space-y-2 text-xs text-[#605F5F]">
                {item.details.map((detail, dIdx) => (
                  <li key={dIdx} className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-black shrink-0" />
                    <span>{detail}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="pt-4 border-t border-[#E6E6E6] text-[10px] font-mono text-[#999999] flex justify-between items-center">
              <span>Verified Output</span>
              <span>JSON Verified</span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
